### ISSUE TITLE
Incorrect escaping of dynamic objects inputs.

### ISSUE THREAD

**Issue by pincher2012** [jbroadway/elefant#245]
jquery.dynamicobjects.js has function:

    self.build_embed_string = function (handler, data) {
        var i, sep = '?', embed = handler;
        for (i in data) {
            embed += sep + i + '=' + escape (data[i]); //Problem here when encode utf-8 characters
            sep = '&';
        }
        return embed;
    };

I can't edit dynamic object with cyrillic parameters after embedding.
I propose to replace the function escape to encodeURIComponent.

https://github.com/jbroadway/elefant/pull/246

**Comment by jbroadway** [comment]
Just merged the PR so I'm closing this out too.
