### ISSUE TITLE
Form validation: Allow multiple error messages per field

### ISSUE THREAD

**Issue by jbroadway** [jbroadway/elefant#267]
If we make one addition to the form validation syntax, we can easily allow multiple validation error messages per field without requiring custom validations in PHP (which would also allow them to work client-side too). Here's an example:

```ini
[email]
not empty = 1 ; failed[] = email

[email:email-invalid]
email = 1 ; failed[] = email-invalid
```

This would correspond to the following template code:

```html
<p>
    <label>{"Email address"}</label><br />
    <input type="email" name="email" value="{{email}}" />
    <span class="notice" id="email-notice">{"Please enter an email address."}</span>
    <span class="notice" id="email-invalid-notice">{"Please enter a valid email address."}</span>
</p>
```

Nothing else ought to need changing in the Form API for this to work.

**Comment by AxorB** [comment]
Very appreciated feature!
