### ISSUE TITLE
can't create new page?

### ISSUE THREAD

**Issue by xmory** [jbroadway/elefant#283]
Hi jbroadway, long time no see. Glad to see you!
When I tried the latest version, I found that I can't create new page. I clicked the submit button, the page refreshed, but new page didn't be created.
Maybe it is a bug ?

**Comment by jbroadway** [comment]
Hey @xmory! Glad to see you too!

I'm not seeing that problem happening on my copy yet. Can you try these things to see if they help:

1. Clear your browser cache. There may be updated Javascript that the browser isn't seeing and causing input validation to fail.
2. If that doesn't work, can you check your server error logs to see if there are any errors.

Let me know if those help or if you see any errors in the logs. Cheers!

**Comment by xmory** [comment]
Ah, yes. After I reinstalled, the problem disappeared.
Thanks for your reply :)
