### ISSUE TITLE
ElefantCMS Community Forum on the Elefant website

### ISSUE THREAD

**Issue by kreativmind** [jbroadway/elefant#284]
Johnny, I've tried to post new discussions 3 times or more and finally was able to. However, the forum is displaying the following error:

{"DiscussionID":"","DraftID":"727","FormSaved":true,"DeliveryType":"VIEW","Data":"PGRpdiBpZD0iRGlzY3Vzc2lvbkZvcm0iIGNsYXNzPSJGb3JtVGl0bGVXcmFwcGVyIERpc2N1c3Npb25Gb3JtIj4KICAgPGRpdiBjbGFzcz0iRm9ybVdyYXBwZXIiPjxmb3JtIG1ldGhvZD0icG9zdCIgYWN0aW9uPSIvZm9ydW0vaW5kZXgucGhwP3A9L3Bvc3QvZGlzY3Vzc2lvbiI+CjxkaXY+CjxpbnB1dCB0eXBlPSJoaWRkZW4iIGlkPSJGb3JtX1RyYW5zaWVudEtleSIgbmFtZT0iVHJhbnNpZW50S2V5IiB2YWx1ZT0iUDVYWlJYR0pWTVFEIiAvPjxpbnB1dCB0eXBlPSJoaWRkZW4iIGlkPSJGb3JtX2hwdCIgbmFtZT0iaHB0IiB2YWx1ZT0iIiBzdHlsZT0iZGlzcGxheTogbm9uZTsiIC8+PGlucHV0IHR5cGU9ImhpZGRlbiIgaWQ9IkZvcm1fRGlzY3Vzc2lvbklEIiBuYW1lPSJEaXNjdXNzaW9uSUQiIHZhbHVlPSIiIC8+PGlucHV0IHR5cGU9ImhpZGRlbiIgaWQ9IkZvcm1fRHJhZnRJRCIgbmFtZT0iRHJhZnRJRCIgdmFsdWU9IjcyNyIgLz48ZGl2IGNsYXNzPSJQIj48ZGl2IGNsYXNzPSJDYXRlZ29yeSI+PGxhYmVsIGZvcj0iRm9ybV9DYXRlZ29yeUlEIj5DYXRlZ29yeTwvbGFiZWw+CiA8c2VsZWN0IGlkPSJGb3JtX0NhdGVnb3J5SUQiIG5hbWU9IkNhdGVnb3J5SUQiPgo8b3B0aW9uIHZhbHVlPSI1Ij5Bbm5vdW5jZW1lbnRzPC9vcHRpb24+CjxvcHRpb24gdmFsdWU9IjQiPkFwcHM8L29wdGlvbj4KPG9wdGlvbiB2YWx1ZT0iMTIiIHNlbGVjdGVkPSJzZWxlY3RlZCI+RGVzaWduPC9vcHRpb24+CjxvcHRpb24gdmFsdWU9IjciPkRvY3VtZW50YXRpb248L29wdGlvbj4KPG9wdGlvbiB2YWx1ZT0iMiI+RnJhbWV3b3JrPC9vcHRpb24+CjxvcHRpb24gdmFsdWU9IjYiPkZ1dHVyZTwvb3B0aW9uPgo8b3B0aW9uIHZhbHVlPSIxMyI+STE4bjwvb3B0aW9uPgo8b3B0aW9uIHZhbHVlPSIxMCI+SW5zdGFsbCBIZWxwPC9vcHRpb24+CjxvcHRpb24gdmFsdWU9IjExIj5NaXNjZWxsYW5lb3VzPC9vcHRpb24+Cjwvc2VsZWN0PjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9IlAiPjxsYWJlbCBmb3I9IkZvcm1fTmFtZSI+RGlzY3Vzc2lvbiBUaXRsZTwvbGFiZWw+CjxkaXYgY2xhc3M9IlRleHRCb3hXcmFwcGVyIj48aW5wdXQgdHlwZT0idGV4dCIgaWQ9IkZvcm1fTmFtZSIgbmFtZT0iTmFtZSIgdmFsdWU9IkxvZ28gd2l0aCBNaW5pbWFsIiBtYXhsZW5ndGg9IjEwMCIgY2xhc3M9IklucHV0Qm94IEJpZ0lucHV0IiAvPjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9IlAiPjxkaXYgY2xhc3M9ImJvZHlib3gtd3JhcCI+PGRpdiBjbGFzcz0iVGV4dEJveFdyYXBwZXIiPjx0ZXh0YXJlYSBpZD0iRm9ybV9Cb2R5IiBuYW1lPSJCb2R5IiBUYWJsZT0iRGlzY3Vzc2lvbiIgZm9ybWF0PSJNYXJrZG93biIgY2xhc3M9IiBUZXh0Qm94IEJvZHlCb3giIHJvd3M9IjYiIGNvbHM9IjEwMCI+TmljZSB0byBzZWUgeW91IGFyb3VuZCBKb2hubnkuIEdyZWF0IHdvcmsgd2l0aCBGbGlwc2lkZS4gSW4gcmVnYXJkcyB0byB0aGUgbG9nbywgd2hpY2ggaXMgdGhlIGNvcnJlY3Qgc2l6ZT8gSSBoYXZlIHRyaWVkIDI0OHg5OHB4IGFuZCBzbWFsbGVyIGJ1dCBldmVyeXRoaW5nIHVwbG9hZGVkIGlzIHNjYWxlZCBsYXJnZXIgYW5kIGRvZXNuJ3QgZml0LiBUaGFua3M8L3RleHRhcmVhPjwvZGl2PjxpbnB1dCB0eXBlPSJoaWRkZW4iIGlkPSJGb3JtX0Zvcm1hdCIgbmFtZT0iRm9ybWF0IiB2YWx1ZT0iTWFya2Rvd24iIC8+PC9kaXY+PC9kaXY+PGRpdiBjbGFzcz0iQnV0dG9ucyI+PGlucHV0IHR5cGU9InN1Ym1pdCIgaWQ9IkZvcm1fUG9zdERpc2N1c3Npb24iIG5hbWU9IlBvc3RfRGlzY3Vzc2lvbiIgdmFsdWU9IlBvc3QgRGlzY3Vzc2lvbiIgY2xhc3M9IkJ1dHRvbiBQcmltYXJ5IERpc2N1c3Npb25CdXR0b24iIC8+CjxpbnB1dCB0eXBlPSJzdWJtaXQiIGlkPSJGb3JtX1NhdmVEcmFmdCIgbmFtZT0iU2F2ZV9EcmFmdCIgdmFsdWU9IlNhdmUgRHJhZnQiIGNsYXNzPSJCdXR0b24gRHJhZnRCdXR0b24iIC8+CjxpbnB1dCB0eXBlPSJzdWJtaXQiIGlkPSJGb3JtX1ByZXZpZXciIG5hbWU9IlByZXZpZXciIHZhbHVlPSJQcmV2aWV3IiBjbGFzcz0iQnV0dG9uIFByZXZpZXdCdXR0b24iIC8+CjxhIGhyZWY9Ii9mb3J1bS9pbmRleC5waHA\/cD0vdmFuaWxsYS9kaXNjdXNzaW9ucyIgY2xhc3M9IkJ1dHRvbiBDYW5jZWwiPkNhbmNlbDwvYT48L2Rpdj48L2Rpdj4KPC9mb3JtPjwvZGl2PjwvZGl2Pgo=","InformMessages":[{"CssClass":"Dismissable AutoDismiss","Message":"Draft saved at 2:55PM"}],"ErrorMessages":"","RedirectUrl":""}

**Comment by jbroadway** [comment]
We finally have a good solution for this since several attempts at upgrading Vanilla Forums failed on me over the last few years. We're now part of the GitHub Discussions beta, so we'll be [moving the forum here from now on](https://github.com/jbroadway/elefant/discussions).
