### ISSUE TITLE
Not working plugin Lemur Learning on version 2.0.7

### ISSUE THREAD

**Issue by aukc1970** [jbroadway/elefant#290]
Not working plugin Lemur Learning on version 2.0.7.  How to make this plugin work on new versions 2.0.7 or 2.0.6 ?

**Comment by lux** [comment]
I was able to install it by adding `"minimum-stability": "dev"` to my composer.json file. It hasn't been updated in several years since the company behind that plugin no longer exists, so while it did install okay there may be things that are broken within it too.
