### ISSUE TITLE
The file Manager cannot be updated in the new 2.0.7 and 2.0.6.

### ISSUE THREAD

**Issue by aukc1970** [jbroadway/elefant#291]
The file Manager cannot be updated in the new 2.0.7 and 2.0.6.
On a fresh install of  2.0.7 , 2.0.6, I get the message "Files (click to upgrade)". When I do, I get this error:

Upgrading App: Files

Upgrade failed on version 1.3.1. Rolling back changes.

Error: SQLSTATE[HY000]: General error: 1 table elefant_filemanager_bitly_link already exists

**Comment by lux** [comment]
I believe this is fixed in the latest update, but here's a post with a way to fix it too:

https://www.elefantcms.com/community#/discussion/1323/error-upgrading
