### ISSUE TITLE
It is not possible to register on the error captcha community forum.

### ISSUE THREAD

**Issue by aukc1970** [jbroadway/elefant#292]
It is not possible to register on the error captcha community forum. Captcha is outdated reCAPTCHA V1 IS SHUTDOWN" or " V1 SHUTDOWN needs update to V2

**Comment by Sinecuraweb** [comment]
pls fix)

**Comment by jbroadway** [comment]
We finally have a good solution for this since several attempts at upgrading Vanilla Forums failed on me over the last few years. We're now part of the GitHub Discussions beta, so we'll be [moving the forum here from now on.](https://github.com/jbroadway/elefant/discussions)
