### ISSUE TITLE
Error: SQLSTATE[HY000]: General error: 

### ISSUE THREAD

**Issue by evan70** [jbroadway/elefant#304]
Hi JB
after clean install of latest version  Elefant CMS 2.2.1 at php 7.1
cant see acounts in admin > 

Upgrading App: Accounts
Upgrade failed on version 1.1.6. Rolling back changes.
Error: SQLSTATE[HY000]: General error: 1 table elefant_api_tmp has 5 columns but 7 values were supplied

web site core throw me error > 
Upgrading Elefant
error: SQLSTATE[HY000]: General error: 1 duplicate column name: background

thank You

**Comment by jbroadway** [comment]
Sorry about that! It looks like I forgot to update the version numbers in the `conf/install_*.sql` files, and it's causing the system to think it needs to upgrade those apps, which it shouldn't actually need to do.

I'll have to fix that and put out an update asap, but in the meantime, I believe it should fix it if you edit the entries in the `elefant_apps` database table and set the version number for each app to whatever the version number is in that app's `app/*/conf/config.php` file. For the "elefant" entry, set it to "2.2.1".

Let me know if that gets it working for you!

**Comment by evan70** [comment]
works Like charm now ;)
thank you for such a quick fix JB

**Comment by lux** [comment]
No problem, glad that worked. It also led to a fix so I don't have to remember to update the app versions in the schema any more :)
