### ISSUE TITLE
add new page problem

### ISSUE THREAD

**Issue by evan70** [jbroadway/elefant#314]
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/emojionearea@3.4.1/dist/emojionearea.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

https://cdn.rawgit.com/yuku-t/jquery-textcomplete/v1.3.4/dist/jquery.textcomplete.js
is 404

thank ya :)

**Comment by jbroadway** [comment]
Just fixed the source mp issue in master (210031191044182d8fb6166b7116193765826c26), but [it doesn't look like](https://github.com/mervick/emojionearea/issues/419) there's a fix for the textcomplete error yet. I might just disable autocomplete, which stops EmojioneArea from trying to load the file.

Hoping to get an update out soon in any case, just testing a cool new multi-column page editing feature :)

**Comment by jbroadway** [comment]
Disabling EmojioneArea's autocomplete seems to fix it 66544ff7ee2c8d213738e4057ac01cebf5c33652.

**Comment by evan70** [comment]
sounds Goood :) Thank ya JB
