### ISSUE TITLE
Unable to install (PHP 8.1?)

### ISSUE THREAD

**Issue by hroma** [jbroadway/elefant#324]
Hi, 
I wanted to test elefant, but after fresh/clean install I get the following issue:
`Debugger::handle_error (2, "Undefined array key "photo"", "\apps\filemanager\handlers\photo.php", 60)`
Is it PHP 8.1 related or else?
Thank for your help

**Comment by lux** [comment]
PHP 8+ is a work in progress [here](https://github.com/jbroadway/elefant/commits/php8-fixes). Many things work but there are a few places that need fixes such as the navigation editor and designer app. Hope to have those fixed soon, but no ETA yet.
